import type { Metadata } from "next"
import { Geist, Geist_Mono, Public_Sans } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/context/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Jobable",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={publicSans.className}
      suppressHydrationWarning
    >
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
